// <auto-generated />
namespace GioiaApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class df12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(df12));
        
        string IMigrationMetadata.Id
        {
            get { return "201806172350479_df12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
