// <auto-generated />
namespace GioiaApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class js : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(js));
        
        string IMigrationMetadata.Id
        {
            get { return "201806250404321_js"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
